= Selenium WebDriver
Igor Chele, Igor Gorea
:revnumber: 1.1
:revdate: 2024-08-16
:doctype: book
:toc: left
:sectnums:
:icons: font
:highlightjs-languages: java

== What is Selenium WebDriver

Selenium WebDriver is a powerful tool for automating web browsers.
It provides a programming interface (API) for interacting with web browsers and automating web application testing.
WebDriver allows you to write code in various programming languages (such as *Java*, Python, C#, etc.) to control web browsers programmatically and perform actions like clicking buttons, filling forms, navigating through pages, and verifying web page contents.

WebDriver supports multiple web browsers such as Chrome, Firefox, Safari, and Edge, allowing you to write tests that run seamlessly across different browsers.

Integration with Testing Frameworks: WebDriver can be integrated with popular testing frameworks like *Cucumber*, *JUnit* and TestNG, enabling the creation of structured and maintainable test suites.

:icons: font

[NOTE]
Support for Parallel Execution: WebDriver supports parallel test execution, allowing you to run tests concurrently across multiple browsers or browser instances, thus reducing test execution time.
This is a more complex solution which is used with WebDriver Factory or WebDriver Manager.

== Dependencies

In order to run it , first we need to install Selenium library (add dependency to pom.xml file) from https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java[here] , otherwise, see an example below.

[source,xml]
----

<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.22.0</version>
    <scope>test</scope>
</dependency>

----

== Selenium Manager

Selenium Manager is a command-line tool implemented in Rust that provides automated driver and browser management for Selenium.
Selenium bindings use this tool by default, so you do not need to download it or add anything to your code or do anything else to use it.

=== Why driver managers exists?

Selenium uses the native support implemented by each browser to carry out the automation process.
For this reason, Selenium users need to place a component called _driver_ (chromedriver, geckodriver, msedgedriver, etc.) between the script using the Selenium API and the browser.
For many years, managing these drivers was a manual process for Selenium users.
This way, they had to download the required driver for a browser (chromedriver for Chrome, geckodriver for Firefox, etc.) and place it in the `PATH` or export the driver path as a system property (Java, JavaScript, etc.).
But this process was cumbersome and led to maintainability issues.

Let’s consider an example.
Imagine you manually downloaded the required chromedriver for driving your Chrome with Selenium.
When you did this process, the stable version of Chrome was 113, so you downloaded chromedriver 113 and put it in your `PATH`.
At that moment, your Selenium script executed correctly.
But the _problem_ is that Chrome is _evergreen_.
This name refers to Chrome’s ability to upgrade automatically and silently to the next stable version when available.
This feature is excellent for end-users but potentially dangerous for browser automation.
Let’s go back to the example to discover it.
Your local Chrome eventually updates to version 115. And that moment, your Selenium script is broken due to the incompatibility between the manually downloaded driver (113) and the Chrome version (115).
Thus, your Selenium script fails with the following error message: _“session not created: This version of ChromeDriver only supports Chrome version 113”_.

This problem is the primary reason for the existence of the so-called _driver managers_ (such as WebDriverManager for Java, webdriver-manager for Python, webdriver-manager for JavaScript, WebDriverManager.Net for C#, and webdrivers for Ruby).
All these projects were an inspiration and a clear sign that the community needed this feature to be built in Selenium.
Thus, the Selenium project has created Selenium Manager, the official driver manager for Selenium, shipped out of the box with each Selenium release as of version 4.6.

=== Usage

_Driver management_ through Selenium Manager _is *opt-in* for the Selenium_ bindings.
Thus, _users can continue managing their drivers manually_ (putting the driver in the PATH or using system properties) or _rely on a third-party driver manager_ to do it automatically.
Selenium Manager only operates as a fallback: if no driver is provided, Selenium Manager will come to the rescue.

:icons: font

[NOTE]
Selenium Manager is a CLI (command line interface) tool implemented in Rust to allow cross-platform execution and compiled for Windows, Linux, and macOS.
The Selenium Manager binaries are shipped with each Selenium release.
This way, each Selenium binding language invokes Selenium Manager to carry out the automated driver and browser management explained in the following sections.

== For those who wants to set drivers manually: Download driver(s)

Next is to download the corresponding driver for our browser, here are some links:

[cols="1,1"]
|===
^|Documentation 📖 ^|Releases 📥

^|https://chromedriver.chromium.org/[About driver for Chrome - chromedriver]
^|https://developer.chrome.com/docs/chromedriver/downloads[Chromedriver Releases]

^|https://github.com/mozilla/geckodriver[About driver for Firefox - geckodriver]
^|https://github.com/mozilla/geckodriver/releases[Geckodriver Releases]

^|https://learn.microsoft.com/en-us/microsoft-edge/?form=MA13LH[About driver for Edge - msedgedriver]
^|https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/?form=MA13LH[Msedgedriver Releases]

^|https://github.com/operasoftware/operachromiumdriver[About driver for Opera - operadriver]
^|https://github.com/operasoftware/operachromiumdriver/releases[Operadriver Releases]
|===

After unpacking , make sure to save the driver in the "resources" directory of the ATF.

'''

=== Basic configuration for a test

To open a URL link the most basic requirements are:

[source,java]
----
package hackerRank;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class BasicTest {
    public static void main(String[] args) {
        WebDriver driver = new ChromeDriver();

        driver.get("https://selenium.dev/documentation/");

        driver.quit();
    }
}
----

See attached a simple example "BasicConfiguration"(separately in JUnit and Cucumber) of a test with some additional commands specific for WebDriver.

'''

=== WebDriver basic commands

==== Here are some examples you might use

* *driver.get(string arg0)* - this method _load_ a new web page in current browser window.
* *driver.navigate().to(string arg0)* - same operation as previous
* *driver.navigate().forward()* - same operation of a _forward button_ of any browser
* *driver.navigate().back()* - same as _back button_
* *driver.navigate().refresh()* - refresh the current page
* *driver.close()* - _close_ only the current browser window

* *driver.quit()* - _closes_ all browser windows and the driver itself
* *driver.manage().windows().maximized()* - maximize browser window
* *driver.getTitle()* - gets the title of the page, if available
* *driver.getCurrentUrl()* - gets the URL
* *driver.switchTo().newWindow(WindowType.TAB)* - opens a new tab and switches to it
* *driver.switchTo().newWindow(WindowType.WINDOW)* - opens a new browser window and switches to it

==== Some outdated commands

* *driver.wait()* - better use awaitility for wait operations
* *driver.findElement()* - POM (Page Object Model) recommended, but might have a special case to be used

[source,java]
----
public class OutDatedNavigationTest {

    @Test
    public void outDatedNavigationTest() {
        System.setProperty("webdriver.chrome.driver", "src/main/resources/drivers/chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        driver.get("https://www.selenium.dev/documentation/webdriver/");
        driver.manage().window().maximize();

        WebElement btnBrowsers = driver.findElement(By.id("m-documentationwebdriverbrowsers"));
        btnBrowsers.click();

        String currentPage = driver.getCurrentUrl();
        Assert.assertEquals("https://www.selenium.dev/documentation/webdriver/browsers/", currentPage);

        driver.quit();
    }
}
----

== Conclusions

WebDriver can have a much more complex configuration to cover the needs of ATF tests execution.

There are *various methods of configurations*, but *the most recommended are* to use *Singleton pattern for browser initiation*
and *to ensure that unused browser sessions to be closed*.

Also, you may check the attached files with an example of WebDriver configuration via WebDriverFactory with browser selection.(in ComplexConfiguration folder)

:icons: font

[NOTE]
WebElements interaction is part of other chapter.