= Operators in Java
Liudmila Topal <liudmila.topal@endava.com>
3.0, July 29, 2022: AsciiDoc article template
:toc:
:icons: font

Java provides many types of operators which can be used according to the need.

They are classified based on the functionality they provide.

=== What are the Operators?
====
*Operators* in Java are the symbols used for performing specific operations in Java.
====

Operators make tasks like addition, multiplication, etc. which look easy although the implementation of these tasks is quite complex.

=== Types of Operators
There are multiple types of operators in Java all are mentioned below:

* link:#arithmetic[Arithmetic Operators]
* link:#unary[Unary Operators]
* link:#assignment[Assignment Operator]
* link:#relational[Relational Operators]
* link:#logical[Logical Operators]
* link:#ternary[Ternary Operator]
* link:#bitwise[Bitwise Operators]
* link:#shift[Shift Operators]
* link:#instanceOf[Instance of operator]

=== The precedence order
There is a precedence order of all arithmetic operators, including parentheses.

The list below is sorted from the highest to the lowest precedence level:

. Parentheses
. Unary plus/minus
. Multiplication, division
. Addition, subtraction

==== [[arithmetic]]Arithmetic Operators
They are used to perform simple arithmetic operations on primitive data types:

* *** : Multiplication
* */* : Division
* *%* : Modulo
* *+* : Addition
* *–* : Subtraction

[NOTE]
=====
link:operators_examples/ArithmeticOperators.java[Here] you can find some examples.
=====

==== [[unary]]Unary Operators
TIP: Unary operators need only one operand.

They are used to increment, decrement, or negate a value.

* *–* : *Unary minus*, used for negating the values.
* *+* : *Unary plus* indicates the positive value (numbers are positive without this, however).
It performs an automatic conversion to int when the type of its operand is the byte, char, or short.
This is called unary numeric promotion.
* ++ : *Increment operator*, used for incrementing the value by 1.
There are two varieties of increment operators:
** *Post-Increment*: Value is first used for computing the result and then incremented.
** *Pre-Increment*: Value is incremented first, and then the result is computed.
* *– –*  : *Decrement operator*, used for decrementing the value by 1.
There are two varieties of decrement operators.
** *Post-decrement*: Value is first used for computing the result and then decremented.
** *Pre-Decrement*: The value is decremented first, and then the result is computed.
* *!*: *Logical not operator*, used for inverting a boolean value.

[NOTE]
=====
link:operators_examples/UnaryOperators.java[Here] you can find some examples.
=====

==== [[assignment]]Assignment Operator
====
‘*=*’ *Assignment operator* is used to assign a value to any variable.
====

It has right-to-left associativity, i.e. value given on the right-hand side of the operator is assigned to the variable on the left,
and therefore right-hand side value must be declared before using it or should be a constant.

The general format of the assignment operator is:

*Syntax:*
[source, java]
----
DataType variableName = initialization;
----

In many cases, the assignment operator can be combined with other operators to build a shorter version of the statement called a Compound Statement.

TIP: For example, instead of a = a + 5, we can write *'a += 5'*.

* *+=*: for adding the left operand with the right operand and then assigning it to the variable on the left.
* *-=*: for subtracting the right operand from the left operand and then assigning it to the variable on the left.
* **=:* for multiplying the left operand with the right operand and then assigning it to the variable on the left.
* */=*: for dividing the left operand by the right operand and then assigning it to the variable on the left.
* *%=*: for assigning the modulo of the left operand by the right operand and then assigning it to the variable on the left.

[NOTE]
=====
link:operators_examples/AssignmentOperators.java[Here] you can find some examples.
=====

==== [[relational]]Relational Operators
====
*These operators* are used to check for relations like equality, greater than, and less than.
====

They return *boolean* results after the comparison and are extensively used in looping statements as well as conditional _if-else statements_.

* *==*: *Equal to* returns _true_ if the left-hand side is equal to the right-hand side.
* *!=*: *Not Equal to* returns _true_ if the left-hand side is not equal to the right-hand side.
* *<*: *Less than* returns _true_ if the left-hand side is less than the right-hand side.
* *< =*: *Less than or equal to* returns _true_ if the left-hand side is less than or equal to the right-hand side.
* *>*: *Greater than* returns *true* if the left-hand side is greater than the right-hand side.
* *> =*: *Greater than or equal to* returns _true_ if the left-hand side is greater than or equal to the right-hand side.

[NOTE]
=====
link:operators_examples/RelationalOperators.java[Here] you can find some examples.
=====

==== [[logical]]Logical Operators

TIP: *Logical operators* are used to determine the logic between variables or values:

* *&&* - *Logical AND*: returns _true_ when _both conditions_ are true.
* *||* - *Logical OR*: returns _true_ if _at least one condition_ is true.
* *!* - *Logical NOT*: returns _true_ when a condition is false and vice-versa.

[NOTE]
=====
link:operators_examples/LogicalOperators.java[Here] you can find some examples.
=====

==== [[ternary]]Ternary operator
The *ternary operator* is a shorthand version of the if-else statement.

It has three operands and hence the name Ternary:

*Syntax:*
[source, java]
----
condition ? if true : if false
----

[NOTE]
=====
link:operators_examples/TernaryOperator.java[Here] you can find some examples.
=====

----
The above statement means that if the condition evaluates to true, then execute the statements after the ‘?’ else execute the statements after the ‘:’.
----

==== [[bitwise]]Bitwise Operators
These operators are used to perform the manipulation of individual bits of a number.

TIP: They can be used with any of the integer types.

* *&* - *Bitwise AND operator*: returns bit by bit AND of input values.
* *|* - *Bitwise OR operator*: returns bit by bit OR of input values.
* *^* - *Bitwise XOR operator*: returns bit-by-bit XOR of input values.
* *~* - *Bitwise Complement Operator*: This is a _unary operator_ which returns the one’s complement representation
of the input value, i.e., with all bits inverted.

[NOTE]
=====
link:operators_examples/BitwiseOperators.java[Here] you can find some examples.
=====

==== [[shift]]Shift Operators
These operators are used to shift the bits of a number left or right, thereby multiplying or dividing the number by two, respectively.

TIP: They can be used when we have to multiply or divide a number by two.

*Syntax:*
[source, java]
----
number shift_operator number_of_places_to_shift;
----

* *<<* - *Left shift operator*: shifts the bits of the number to the left and fills 0 on voids left as a result.
Similar effect as multiplying the number with some power of two.
* *>>* - *Signed Right shift operator*: shifts the bits of the number to the right and fills 0 on voids left as a result.
The leftmost bit depends on the sign of the initial number.
Similar effect to dividing the number with some power of two.
* *>>>* - *Unsigned Right shift operator*: shifts the bits of the number to the right and fills 0 on voids left as a result.
The leftmost bit is set to 0.

[NOTE]
=====
link:operators_examples/ShiftOperators.java[Here] you can find some examples.
=====

==== [[instanceOf]]Instance of operator
The instance of the operator is used for type checking.

TIP: It can be used to test if an object is an instance of a class, a subclass, or an interface.

*Syntax:*
[source, java]
----
object instance of class/subclass/interface
----

[NOTE]
=====
link:operators_examples/InstanceOfOperator.java[Here] you can find some examples.
=====

=== Advantages of Operators
The advantages of using operators in Java are mentioned below:

* *Expressiveness*: Operators in Java provide a concise and readable way to perform complex calculations and logical operations.
* *Time-Saving*: Operators in Java save time by reducing the amount of code required to perform certain tasks.
* *Improved Performance*: Using operators can improve performance because they are often implemented at the hardware level,
making them faster than equivalent Java code.