= Test Hooks. Before & After.
Igor Chele
:revnumber: 1.1
:revdate: 2024-08-16
:doctype: book
:toc: left
:sectnums:
:icons: font
:highlightjs-languages: java

== HOOKS

In the context of Cucumber for Java, Hooks are blocks of code that run before or after scenarios.
They allow you to set up and tear down the test environment, perform setup and cleanup tasks,
and handle scenarios at various stages of execution. Hooks provide a way to execute common code across multiple scenarios,
improving code reusability and maintainability.
Although Hooks can be written in a step definition file, a more common practice is to place them in a separate class.
Cucumber Java supports several types of Hooks, including:

- *Before Hooks*: These hooks run before each scenario and are typically used to set up the
   test environment or perform preconditions necessary for the scenario to execute.
   For example, you might use a before hook to open a web browser, initialize test data,
   or authenticate users. Tags can be used to separate conditions required for special tests.


- *After Hooks*: These hooks run after each scenario and are used to clean up the test environment
   or perform post-execution tasks. After hooks are commonly used to close resources, log results,
   or capture screenshots after the scenario has completed.


- *BeforeStep and AfterStep Hooks*: These hooks run before and after each step within a scenario,
   allowing you to execute setup and cleanup tasks at a finer granularity. They are useful for
   scenarios where you need to perform actions before or after each step, such as logging step
   execution or taking screenshots.


- *Around Hooks*: Cucumber Java also supports around hooks, which wrap the execution of each
   scenario and allow you to perform custom actions before and after scenario execution.
   Around hooks are more flexible than before and after hooks because they can control the entire
   scenario execution flow.


- *BeforeAll and AfterAll Hooks* are used for same purposes as Before and After in case there is a separation of
   preconditions required for specific tests divided by some tags (as : UI, API, Regression, Production,
   Sanity and others), still some general preconditions are required in order to start any test pack.

== Attributes used with Hooks

- **Tags** - Tags are applied especially for Cucumber scenarios and features, hence the need to prepare specific
  preconditions or execute specific actions at the end of tests related to those. Most common are the ones that  
  represents test suites as : "@smoke", "@regression", "@sanity"; separate test types : "@UI", "@ui_tests", "@API",
  "@api_tests"; different environments as : "@Dev", "@Test", "@Integration", "@Pre_Prod".


- **order** - several @Before can be present with different methods - in this case an order number is used
  and hooks are executed according that order number in *ascending* order >> order 1, order 2,order 3...
  In case of multiple @After with specified order number the execution is according order number in *descending*
  order >> ... order 3, order 2, order 1.


- **timeout** - takes a value representing the maximum time (in milliseconds) that the hook method is allowed
  to execute before it is considered timed out. If it takes longer Cucumber will abort the execution and mark it as
  failed. This prevents test scenarios from hanging indefinitely due to unexpected issues in setup or teardown
  operations.


== Examples

*The simple Hooks configuration as a separate class.*

[source,java]
----
package hooks;

import io.cucumber.java.After;
import io.cucumber.java.Before;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Hooks {
    public static WebDriver driver;

    @Before
    public void launchBrowser() {
        driver = new ChromeDriver();
        driver.manage().window().maximize();
    }

    @After
    public void tearDown() {
        driver.close();
        driver.quit();
    }
}
----

*TestRunner class with "hooks" package in glue (path to Hooks class).*

[source,java]
----
package runner;


import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
@CucumberOptions(
        features = "src/test/resources/features",
        glue = {"stepDefinitions", "hooks"},
        monochrome = true,
        plugin = {"pretty"}
)

public class TestRunner {
}
----

'''

*A more complex example of the Hooks class:*

- In this case, we have a specific separation of UI and API tests with tags "@UI"/"@API".
- @BeforeAll and @AfterAll hooks are used for both types of tests.
- @AfterStep hook is utilized to save a screenshot as detailed evidence for UI tests.
- Every hook has some information logged, it is recommended to add scenario name to the @Before hook.

[source,java]
----
package hooks;

import api.Authorization;
import io.cucumber.java.*;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.AfterEach;
import utils.ScenarioContext;
import utils.WebDriverFactory;

public class Hooks {
    private static final Logger logger = LogManager.getLogger(Hooks.class);

    @BeforeAll
    public static void launchTests() {
        ScenarioContext.getScenarioInstance().clearContext();
        logger.info("Test/s started");
    }

    @Before("@API")
    public static void setUpAPI(Scenario scenario) {
        logger.info(System.lineSeparator() + "Starting API test: " + scenario.getName());
        Authorization.authorization();
    }

    @Before("@UI")
    public static void launchBrowser(Scenario scenario) {
        logger.info(System.lineSeparator() + "Starting UI test: " + scenario.getName());
        WebDriverFactory.getWebDriver();
    }

    @Before(order = 1, value = "@UI_Desktop")
    public static void getDesktopSize() {
        DeviceManager.getDesktopResolution();
        logger.info("Desktop resolution is retrieved");
    }

    @Before(order = 2, value = "@UI_Desktop")
    public static void maximizeBrowser() {
        WebDriverFactory.openNewBrowser();
        WebDriverFactory.maximizeBrowserWindow();
        logger.info("Browser maximized to desktop size");
    }

    @Before(order = 1, value = "@UI_Phone")
    public static void getPhoneSize() {
        DeviceManager.getPhoneResolution();
        logger.info("Phone resolution is retrieved");
    }

    @Before(order = 2, value = "@UI_Phone")
    public static void minimizeBrowser() {
        WebDriverFactory.openNewBrowser();
        WebDriverFactory.minimizeBrowserWindow();
        logger.info("Browser minimized to phone size");
    }

    @After("@UI")
    public static void afterScenario(Scenario scenario) {
        WebDriverFactory.takeScreenshot(scenario);
        WebDriverFactory.closeBrowserWindow();
        logger.info("Scenario " + scenario.getName() + " finished");
    }

    @AfterStep("@UI_Detailed")
    public static void detailedTestEvidence(Scenario scenario) {
        WebDriverFactory.takeScreenshot(scenario);
        logger.info("Test evidence saved as screenshot");
    }

    @AfterAll(timeout = 5000)
    public static void closeTests() {
        WebDriverFactory.tearDown();
        ScenarioContext.getScenarioInstance().clearContext();
        logger.info("Test/s finished");
    }
}
----

=== Explanation:

- @BeforeAll hook is used for cleaning any saved values from previous runs.
- @Before("@API") has a specific method for authentication (to extract the token which is requested for POST/GET
  requests later).
- @Before("@UI") has method which gets the browser type, opens it and maximize it, additional can be added other
  method which opens a new browser tab/window.
- @After("@UI") has 2 methods : one to take and save a screenshot of test evidence and other to close the browser window
- @AfterStep - makes a screenshot of every-step.
- @AfterAll - with timeout implemented - includes a method which close all browser windows(webDriver also) and other
  that clears all temporary saved data in Scenario Context.

== Conclusions

Hooks helps us prepare specific conditions for testing, especially useful in complex projects with several test
environments (Production, UAT, Dev, PreProd), UI/API tests, several specific test packs (like Regression, Sanity, Smoke,
other).

 What does our "friend" ChatGPT think about the use of hooks?

Hooks in Cucumber are incredibly useful for various reasons:

- *Code Re-usability*: Hooks allow you to define setup and teardown actions once and apply them to multiple scenarios.
This promotes code re-usability and reduces duplication of code.

- *Consistent Setup*: Hooks ensure that each scenario starts with a consistent setup. This is important for maintaining
the integrity of the tests and ensuring they run reliably.

- *Resource Management*: Hooks help manage resources such as database connections, browser sessions, or test data
initialization. They ensure that resources are properly initialized before tests run and cleaned up afterward.

- *Logging and Reporting*: Hooks can be used to log important information or capture screenshots before and after each
scenario. This aids in debugging and troubleshooting test failures.

- *Test Environment Configuration*: Hooks can set up the test environment before executing scenarios. This includes
tasks such as starting servers, deploying applications, or configuring test-specific settings.

- *Test Data Preparation*: Hooks can be used to prepare test data before scenarios execute. This ensures that scenarios
have the necessary data to execute successfully.

- *Cleanup Activities*: Hooks are valuable for performing cleanup activities after scenarios execute. This includes tasks
such as closing browser windows, deleting temporary files, or releasing resources.