= Utility libraries
Verginia Stolear, Sabrina Graur
:revnumber: 1.1
:revdate: 2024-08-16
:doctype: book
:toc: left
:sectnums:
:icons: font
:source-highlighter: highlightjs
:highlightjs-languages: java, xml

== Introduction to Utility libraries ==

Utility libraries refer to collections of reusable functions, classes and routines that provide common functionality to simplify programming tasks.
It contains low level code used by many libraries.
These libraries are designed to assist developers by offering pre-built, generic functions that can be easily integrated into their applications.
These libraries often cover a wide range of areas, including data structures, input/output operations, concurrency, string manipulation, and more.
Here are some popular utility libraries in Java:

1. Apache Commons Lang:
- Provides a variety of utility classes for working with strings, arrays, numbers, and more.
2. Apache Commons Collections:
- Offers additional collection classes and utilities that complement the Java Collections Framework.
3. Apache Commons IO:
- Contains utilities for working with input/output operations, such as file and stream handling.
4. Guava:
- Developed by Google, Guava provides a set of core libraries for Java, including collections, caching, functional programming, and more.
5. Jackson:
- A popular JSON processing library that facilitates working with JSON data, including data binding and streaming.
6. Log4j:
- A widely-used logging framework that allows flexible configuration and efficient logging in Java applications.
7. Slf4j (Simple Logging Facade for Java):
- Provides a simple facade or abstraction for various logging frameworks, allowing developers to use their preferred logging implementation.
8. JUnit:
- A widely-used testing framework for Java that supports the creation and execution of unit tests.
9. Commons Math:
- A library for mathematical and statistical operations, offering a wide range of functions and algorithms.
10. Lombok:
- A library that simplifies the boilerplate code in Java, reducing the amount of code needed for getters, setters, constructors, and more.
11. Datafaker:
- A library for Java and Kotlin to generate fake data.
12. Awaitility:
- A library which provides a simple domain-specific language (DSL) for asynchronous systems testing.
Allows to define the expectations of async operations within tests - without having to deal with threads, timeouts and other concurrency issues.

These utility libraries are widely used in Java development and can significantly enhance productivity by providing pre-built, well-tested functionality that can be easily integrated into projects.

== Data Faker ==

Datafaker is a library for Java and Kotlin to generate fakedata.
This can be very helpful when generating test data to fill a database, to generate data for a stress test, or anonymize data from production services. +
*Datafaker* is the modern fork for *Javafaker*.
It was transferred to Java 8 and underwent improvements, increasing the library’s performance.
However, the current API stayed more or less the same. +
Thus, previously used Javafaker won’t have any problems migrating to Datafaker.

=== Installation ===

The latest version of Datafaker is 2.1.0. It can be included in your pom.xml:

[source,xml]
----
<!-- https://mvnrepository.com/artifact/net.datafaker/datafaker -->
<dependency>
    <groupId>net.datafaker</groupId>
    <artifactId>datafaker</artifactId>
    <version>2.1.0</version>
</dependency>
----

=== Usage ===

Apply Datafaker to generate fake data, you can use the following code as an example:

[source,java]
----
import net.datafaker.Faker;

Faker faker = new Faker();

String name = faker.name().fullName();
        String firstName = faker.name().firstName();
        String lastName = faker.name().lastName();
        String streetAddress = faker.address().streetAddress();
----

Possible Output:

----
Francisca
O'Conner
Andrew Rosenbaum III
94741 Merle Courts
----

=== Advanced usage ===

Datafaker, as well as Javafaker, support generating values based on the provided pattern.
Datafaker introduced additional functionality added on Advanced usage section with emphasis on:

https://www.datafaker.net/documentation/sequences/[Sequences] +
https://www.datafaker.net/documentation/date-format/[Date format] +
https://www.datafaker.net/documentation/expressions/[Expressions] +
https://www.datafaker.net/documentation/formats/[Formats] +
https://www.datafaker.net/documentation/schemas/[Transformation schemas] +
https://www.datafaker.net/documentation/unique-values/[Unique values] +

For example, regexify is a more flexible way of creating formatted String values.
We can use the regexify directive as an expression or call the regexify method directly on the Faker object:

[source,java]
----
public class Regexify {
    private static Faker faker = new Faker();

    public static void main(String[] args) {
        System.out.println("Expression: " + getExpression());
        System.out.println("Regexify with a method: " + getMethodExpression());
    }

    static String getExpression() {
        return faker.expression("#{regexify '(hello|bye|hey)'}");
    }

    static String getMethodExpression() {
        return faker.regexify("[A-D]{4,10}");
    }
}
----

Possible Output:

----
Expression: bye
Regexify with a method: DCCC
----

For more information and a full list of all the fake data you can access the https://www.datafaker.net/documentation/getting-started/[link]

== Awaitility ==

Awaitility — a library which provides a simple domain-specific language (DSL) for asynchronous systems testing.
With Awaitility, we can express our expectations from the system in an easy-to-read DSL.

=== Installation ===

The latest version of Awaitility is 4.2.0. It can be included in your pom.xml:

[source,xml]
----
<!-- https://mvnrepository.com/artifact/org.awaitility/awaitility -->
<dependency>
    <groupId>org.awaitility</groupId>
    <artifactId>awaitility</artifactId>
    <version>4.2.0</version>
    <scope>test</scope>
</dependency>
----

=== Usage ===

Apply Awaitility for testing using the following code as an example:

[source,java]
----
import static org.awaitility.Awaitility.await;
//..

public EmployeeListPage ClickEmployeeList() {

       await("Wait for the link to be displayed").atMost(TEN_SECONDS)
       .until(lnkEmployeeList::isDisplayed, is(true));
    }
----

or using lambda expression

[source.try-it,java]
----
//..
await().atMost(TEN_SECONDS)
.untilAsserted(()->Assert.assertEquals("Wait for the link to be displayed",lnkEmployeeList.isDisplayed(),true));
----

Sometimes, we have a situation where a method throws an exception before an asynchronous job is done.
Awaitility provides the possibility of ignoring this exception without failing a test.

[source.try-it,java]
----
//..
await().atMost(TEN_SECONDS)
.ignoreExceptions()
.untilAsserted(()->Assert.assertEquals("Wait for the link to be displayed",lnkEmployeeList.isDisplayed(),true));
----

For more details and detailed explanations for other possibilities you can access the http://www.awaitility.org/[awaitility site] and https://github.com/awaitility/awaitility/wiki/Usage[usage guide]

== Resources ==

- https://nx.dev/concepts/more-concepts/library-types
- https://www.datafaker.net/documentation/getting-started/
- https://www.baeldung.com/java-datafaker
- http://www.awaitility.org/
- https://github.com/awaitility/awaitility/wiki/Usage
- https://www.baeldung.com/awaitility-testing
- https://www.mastertheboss.com/various-stuff/testing-java/testing-with-awaitility-made-simple/#google_vignette
- https://www.youtube.com/watch?v=KbmpBZO4EoY
