:doctype: book
:toc: left
:sectnums:

== Generics in Collections

In this chapter, we will explore the powerful concept of generics in collections.
Generics provide a way to create classes, interfaces, and methods with placeholders for data types.
This flexibility allows us to design and use generic collections, enabling type-safe and reusable code.

=== Generic Lists

====
Generic lists are dynamic collections that can hold elements of a specific type.
Unlike non-generic lists, which can store any object, generic lists enforce type safety, reducing the risk of runtime errors.
We'll delve into the syntax, advantages, and common use cases of generic lists.

[source,java]
----
List<Integer> integerList = new ArrayList<>();
----
====

=== Generic Sets

====
Sets are unordered collections that do not allow duplicate elements.
With generics, we can create type-specific sets, ensuring that only elements of a particular type can be added.
We'll explore the features of generic sets, such as type safety and the HashSet and TreeSet implementations.

[source,java]
----
HashSet<string> stringSet = new HashSet<string>();
----
====

=== Generic Maps

====
Generic maps, often known as dictionaries or associative arrays, allow us to store key-value pairs with type specificity.
This section will cover the implementation and usage of generic maps, including popular implementations like HashMap and TreeMap.

[source,java]
----
Map<String, Integer> ageMap = new HashMap<>();
----
====