= Static class in Java
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

In Java, *static* is a keyword that manage objects in the memory.

TIP: A class can be declared static only if it is a *nested class*.

It does not require any reference on the outer class.

The property of the static class is that it does not allow us to access the non-static members of the outer class.

== Properties of the static class

The properties of the static class are:

* The class has only static members.
* It cannot access the member (non-static) of the outer class.
* We cannot create an object of the static class.

====
We can use the static keyword with variables, methods, blocks, and classes.

Using the static class is a way of grouping classes together. It is also used to access the primitive member of the enclosing class through the object reference.

The static classes are loaded by the classloader at the time of the first usage only, not when its enclosing class gets loaded.
====